import { describe } from "node:test";

export const packetData = {
    dataItems: [
        {
            title: "Salepage Page Website",
            subtitle: "เหมาะสำหรับโปรโมทธุรกิจ ขายสินค้า / บริการ",
            price: "15,000฿",
            Description: [
                { describetion: "ออกแบบเว็บไซต์จำนวน 1 " },
                { describetion: "รองรับการแสดงผลทุกหน้าจอ" },
                { describetion: "ฟรี โดเมน (Domain)" },
                { describetion: "พื้นที่เก็บข้อมูล 5 GB" },
                { describetion: "ฟรี รูปภาพประกอบเว็บไซต์" },
                { describetion: "ฟรี ช่องทางการติดต่อ" },
                { describetion: "ฟรี แบบฟอร์มติดต่อสอบถาม" },
                { describetion: "มีระบบจัดการหลังบ้าน แก้ไขข้อมูลได้ด้วยตัวเอง" },
                { describetion: "เว็บไซต์รองรับการทำ SEO" },
                { describetion: "แก้ไขงานได้ไม่เกิน 5 ครั้ง" },
                { describetion: "ดูแลระบบความปลอดภัยตลอดอายุการใช้งาน" },
                { describetion: "ต่ออายุปีละ 3,000 บาท" },
            ]
        },
        {
            title: "Starter Packege",
            subtitle: "เหมาะสำหรับธุรกิจ องค์กร / บริการ",
            price: "25,900฿",
            Description: [
                { describetion: "ออกแบบเว็บไซต์จำนวน 3-5 " },
                { describetion: "Sub Menu 3-5 หน้า" },
                { describetion: "รองรับการแสดงผลทุกหน้าจอ" },
                { describetion: "ฟรี โดเมน (Domain)" },
                { describetion: "พื้นที่เก็บข้อมูล 15 GB" },
                { describetion: "ฟรี รูปภาพประกอบเว็บไซต์" },
                { describetion: "ฟรี ช่องทางการติดต่อ" },
                { describetion: "ฟรี แบบฟอร์มติดต่อสอบถาม" },
                { describetion: "มีระบบจัดการหลังบ้าน แก้ไขข้อมูลได้ด้วยตัวเอง" },
                { describetion: "เว็บไซต์รองรับการทำ SEO" },
                { describetion: "แก้ไขงานได้ไม่เกิน 5 ครั้ง" },
                { describetion: "ดูแลระบบความปลอดภัยตลอดอายุการใช้งาน" },
                { describetion: "ต่ออายุปีละ 3,500 บาท" },
            ]
        },
        {
            title: "Business Packege",
            subtitle: "เหมาะสำหรับธุรกิจ แสดงรายละเอียดสินค้า / บริการ",
            price: "34,900฿",
            Description: [
                { describetion: "ออกแบบเว็บไซต์จำนวน 4-8 " },
                { describetion: "Sub Menu 8-10 หน้า" },
                { describetion: "รองรับการแสดงผลทุกหน้าจอ" },
                { describetion: "ฟรี โดเมน (Domain)" },
                { describetion: "พื้นที่เก็บข้อมูล 20 GB" },
                { describetion: "ฟรี รูปภาพประกอบเว็บไซต์" },
                { describetion: "ฟรี ช่องทางการติดต่อ" },
                { describetion: "ฟรี แบบฟอร์มติดต่อสอบถาม" },
                { describetion: "มีระบบจัดการหลังบ้าน แก้ไขข้อมูลได้ด้วยตัวเอง" },
                { describetion: "ตะกร้าสินค้า สั่งซื้อสินค้าออนไลน์" },
                { describetion: "ลงสินค้า 30 รายการ" },
                { describetion: "เพิ่มลบสินค้าได้ด้วยตัวเอง" },
                { describetion: "มีระบบหมวดหมู่" },
                { describetion: "เว็บไซต์รองรับการทำ SEO" },
                { describetion: "แก้ไขงานได้ไม่เกิน 5 ครั้ง" },
                { describetion: "ดูแลระบบความปลอดภัยตลอดอายุการใช้งาน" },
                { describetion: "ต่ออายุปีละ 4,000 บาท" },
            ]
        },
        {
            title: "E - Commerce Packege",
            subtitle: "เหมาะสำหรับร้านค้า แบบครบวงจร",
            price: "43,000฿",
            Description: [
                { describetion: "ออกแบบเว็บไซต์จำนวน 5-10 " },
                { describetion: "Sub Menu 8-10 หน้า" },
                { describetion: "รองรับการแสดงผลทุกหน้าจอ" },
                { describetion: "ฟรี โดเมน (Domain)" },
                { describetion: "พื้นที่เก็บข้อมูล 25 GB" },
                { describetion: "ฟรี รูปภาพประกอบเว็บไซต์" },
                { describetion: "ฟรี ช่องทางการติดต่อ" },
                { describetion: "ฟรี แบบฟอร์มติดต่อสอบถาม" },
                { describetion: "มีระบบจัดการหลังบ้าน แก้ไขข้อมูลได้ด้วยตัวเอง" },
                { describetion: "ระบบร้านค้า" },
                { describetion: "มีระบบ Fillter หมวดหมู่สินค้า / บริการ" },
                { describetion: "ตะกร้าสินค้า สั่งซื้อสินค้าออนไลน์" },
                { describetion: "ลงสินค้า 30 รายการ" },
                { describetion: "เพิ่มลบสินค้าได้ด้วยตัวเอง" },
                { describetion: "คูปองส่วนลด" },
                { describetion: "ระบบสมาชิก" },
                { describetion: "มีระบบหมวดหมู่" },
                { describetion: "ระบบหลังบ้านบ้านร้านค้า" },
                { describetion: "ระบบจัดการสถานะ Order" },
                { describetion: "รองรับการชำระเงินแบบบัตรเครดิต/โอนเงินเข้าบัญชีธนาคาร และแบบฟอร์มแจ้งการโอนเงิน" },
                { describetion: "เว็บไซต์รองรับการทำ SEO" },
                { describetion: "แก้ไขงานได้ไม่เกิน 5 ครั้ง" },
                { describetion: "ดูแลระบบความปลอดภัยตลอดอายุการใช้งาน" },
                { describetion: "ต่ออายุปีละ 4,500 บาท" },
            ]
        },
    ]
}